### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cjlcarvalho** [cjlcarvalho/LogisticApp#4]
Incluir as classes, interfaces ou métodos abaixo:

- [x] _RotaNotFoundException_ [ incluir no pacote **LogisticApp.exception** ]
- [x] _Rota retrieveByName(String name)_ [ **IRotaDAO** ]
- [x] _Collection< Integer, String > recuperarRotasPorNome(String nome)_ [ **ICadastroRotaSession** ]
- [x] _Collection< Integer, String > recuperarLocalidades()_ [ **ICadastroRotaSession** ]
- [x] _Collection< Integer, String > recuperarLocalidades()_ [ **IContratacaoTransporteSession** ]

**Comment by cjlcarvalho** [comment]
Essa RotaNotFoundException será usada tanto pelo campo de pesquisa de trecho no [panel de Rota Fracional](https://github.com/cjlcarvalho/LogisticApp/blob/master/UI-prototype/rota-fracional.png) quanto pela interface de Contratação de Transporte, quando o usuário for recuperar pelas localidades. É necessário verificar qual será o comportamento dos dois e a mensagem de erro lançada, pois ambos irão lançar alertas diferentes, contudo acho que pode ser a mesma exception.

**Comment by cjlcarvalho** [comment]
@ADSmarcossobral Fiz o merge do seu commit. Só que precisamos ver como a exception vai tratar no caso de não encontrar a Rota pelas localidades origem e destino. Olha o método retrieveByOriginDestiny de RotaDAOSQL, é ele que vai lançar a exceção. Tava pensando em lançá-la quando a Collection ficasse vazia. Os outros métodos da session já estão com o throws para lançarem uma exceção genérica para a view, então basta tratar essa exception na view para mostrar o popup de alerta.

**Comment by ADSmarcossobral** [comment]
Aaah! Certo.

**Comment by cjlcarvalho** [comment]
Acabei mudando RotaNotFoundException para que ela receba uma mensagem mesmo.

**Comment by ADSmarcossobral** [comment]
Roger that!
